FROM linuxkit/alpine:7f3944798557de5518a56e3437d7ed982701f224 AS mirror

RUN apk add --no-cache go musl-dev build-base

COPY . /go/src/github.com/moby/vpnkit
RUN go-compile.sh /go/src/github.com/moby/vpnkit/go/cmd/dial-example
